### ISSUE TITLE
FR: Decouple user_tags from snmp-base.yaml

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#160]
As a user, I need the ability to supply an external file to map `user_tags` to `devices` in my `snmp-base.yaml` configuration file. This would involve matching tags to devices based on defined rules that accept wildcards to align on attributes on the device config element.

e.g.

snmp-base.yaml:
```yaml
devices:
  router1:
    device_name: router1-core
    ...
    user_tags: @user_tags.yaml
```

user_tags.yaml
```yaml
match_rules:
  - device_name: *core*
  - provider: kentik-router
user_tags:
  - environment: production
  - location: dc01
```
