### ISSUE TITLE
FR: "Ping Only" devices

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#192]
As a user, I need the ability to define devices as "ping only" in order to gather availability metrics from devices that do not support SNMP. This closes functional parity with legacy NPM tools and allows me to create entities in NR to provide full coverage monitoring.

example: 

```yaml
devices:
  deviceOne:
    device_name: endpoint123
    device_ip: 192.168.0.254
    provider: kentik-ping
    ping_only: true
```
