### ISSUE TITLE
Feat: IP as failsafe device_name 

### ISSUE THREAD

**Issue by Mesverrum** [kentik/ktranslate#274]
Customer recently presented us with some devices that return nulls on SysName 1.3.6.1.2.1.1.5.0.  Other than that oddity they are collecting data as kentik-defaults using the base profile, but no entity showed up in NR because we require a device_name to create an entity.

We don't usually want to use IP to define the entity because that gets messy in cases where a device has multiple IP's or changes IP, but in this edge case it could have potentially saved them from getting stuck and logging a support case if we could get ktranslate to present something, IP being the logical choice when we have a null SysName.

See below relevant lines from their snmb-base.yaml
```
devices:
  __10.57.7.3:
    device_name: ""
    device_ip: xx.xx.xx.xx
    snmp_comm: foo
    oid: .1.3.6.1.4.1.50001
    description: Hikvision company products
    mib_profile: base.yml
    provider: kentik-default
    discovered_mibs:
    - IF-MIB
    - IP-MIB
    - OSPF-MIB
    - TCP-MIB
    - UDP-MIB
```
