### ISSUE TITLE
💡 FR - Add support for `ignore_list` in Discovery jobs

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#287]
As a user, I need the ability to create an *"ignore list"* in my Discovery config that essentially instructs ktranslate to skip specific IP addresses. 

Use Case: My branch office has a `176.16.1.0/24` subnet that I need to run discovery against, but I know that the `172.16.1.5 - 172.16.1.10` devices are servers that I never want monitored via ktranslate.

Potential solution:

```yaml
discovery:
  cidrs:
  - 172.16.1.0/24
  ignore_list:
  - 172.16.1.5
  - 172.16.1.6
  - 172.16.1.7
  - 172.16.1.8
  - 172.16.1.9
  - 172.16.1.10
```
