### ISSUE TITLE
Feature: Option to discover cidr blocks without portscan

### ISSUE THREAD

**Issue by Mesverrum** [kentik/ktranslate#311]
For cases where tcp port scans are relatively locked down and the /32 individual host method is tedious can we get an option to do a CIDR scan where we go straight into the SNMP check without any preconditions.  With the understanding that this process would be a slower job to complete, but has more coverage.

**Comment by i3149** [comment]
Added `check_all_ips` in the discovery yaml section. This adds this functionality if set to true. 

```
discovery:
  cidrs:
  - 10.10.0.1/24
  ignore_list: []
  check_all_ips: true
  ports:
  - 161
  default_communities:
  - public
```
