### ISSUE TITLE
FR: Add ordered list of profile REs

### ISSUE THREAD

**Issue by i3149** [kentik/ktranslate#317]
```
matches_list:
  - regex: "^pfsense"
    target: pf_sense.yml
  - regex: "barracuda email security gateway"
    target:  barracuda-email-gateway.yml
```

Make the above work as a profile section. This is in addition to the existing `matches` section, which will be deprecated.
