### ISSUE TITLE
Missing devices in discovery process

### ISSUE THREAD

**Issue by travisroberts-sf** [kentik/ktranslate#330]
we have a CIDR block with a /24 configured and yet there are a handful of devices that aren't being discovered, yet ARE responding to snmpwalk requests.

**Comment by thezackm** [comment]
@travisroberts-sf - during discovery, there is a liveliness probe that scans all known TCP ports to check if an IP address is "available" (outlined in [our docs site](https://docs.newrelic.com/docs/network-performance-monitoring/troubleshooting/snmp-discovery-no-devices)). Devices with heightened security postures will often fail to respond to this check and then be skipped during discovery by default.

To work around this you can either target individual devices directly in your `discovery.cidrs`  block:

```yaml
discovery:
  cidrs:
  - 192.168.0.0/24
  - 192.168.0.12/32
```

*In this example, the `192.168.0.12` device will skip the liveliness probe and have only the SNMP testing performed.*

Or you can enable the `discovery.check_all_ips` setting:

```yaml
discovery:
  cidrs:
  - 192.168.0.0/24
  ...
  check_all_ips: true
```

*In this example, every IP address in the CIDR range will skip the liveliness probe and have only the SNMP testing performed.*

Can you please test at your convenience and report back with results?

cc: @araddas
