### ISSUE TITLE
💡 FR - `CPUIdle` tag support from SNMP profiles

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#375]
As a user, I need the ability to annotate specific metrics as `CPUIdle` in SNMP profiles and have ktranslate pre-calculate the actual CPU Utilization metric before export, similar to the patterns used for memory utilization today.

Expected results -

SNMP Profile:
```yaml
  - MIB: UCD-SNMP-MIB
    symbol:
      name: ssCpuIdle
      OID: 1.3.6.1.4.1.2021.11.11.0
      poll_time_sec: 60
      tag: CPUIdle
```

ktranslate:
```
  If(CPUIdle){ 
    CPU == (100 - CPUIdle)
 } Else CPU
```

resulting metrics for export:
```
kentik.snmp.CPU
kentik.snmp.CPUIdle
```
