### ISSUE TITLE
metrics tag "neighbor_ip" collision between the MIBs

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#397]
I have an issue with the BGP-MIB table profile where neighbor_ip tag is not showing in the influxdb output.
On the OSPF-MIB side, sometime I am missing neighbor_ip, sometimes neighbor_id and sometimes both. 

It seems that some collision happens with the same tag name across different MIBs. When I removed OSPF-MIB from collection, the BGP-MIB table output started to show up with neighbor_ip tag in influxdb output.

**Comment by i3149** [comment]
Wait -- there's `neighbor_id` (with a d) in OSPF and neighbor_ip (with a p) in BGP. So I think its just the `d/p` difference?

**Comment by dpajin-kentik** [comment]
in OSPF there are both P and D (neighbor_id and neighbor_ip) and the P one is overlapping with the neighbor_ip from BGP, causing that it does not appear in the BGP. 
My impression is that both tags and metrics need to be unique in names, as if there is overlapping of the names/tags they don't show up on all required places. 

```
    metric_tags:
      - column:
          OID: 1.3.6.1.2.1.14.11.1.3
          name: ospfVirtNbrIpAddr
        tag: neighbor_ip
      - column:
          OID: 1.3.6.1.2.1.14.11.1.2
          name: ospfVirtNbrRtrId
        tag: neighbor_id
```

For example, neighbor_id with D, also sometimes is missing, but it also exist in the ospf-mib.yml under
 - MIB: OSPF-MIB 
but in several tables like ospfNbrTable, ospfVirtNbrTable, ospfIfTable, ospfVirtIfTable. 
I think this causes that is shows up only on one but not at the other, but the same is across different "- MIB " statements and files. 

The uniqueness of the tags and metric names should be only required at the MIB+Table level or just MIB in case of the scalar OIDs. Otherwise, the concept of configurable names is not usable, as neighbor_ip exists in every routing protocol, OSPF, BGP, ISIS plus others like LDP, LLDP, CDP, BFD, etc..
