### ISSUE TITLE
static metric values not working

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#460]
For the profile

```
- MIB: IP
  table:
    OID: .1.3.6.1.2.1.55.1.8
    name: ipv6_address_metadata
  symbols:
    - OID: .1.3.6.1.2.1.55.1.8.1.5
      name: ipv6AddrStatus
      tag: ipv6_address_status

    - name: ipv6_address_static_value_1
      OID: 1.3.6.1.6.3.1136.6169.3
    - name: ipv6_address_static_value_2
      OID: "1.3.6.1.6.3.1136.6169.this_is_random_text2"

  metric_tags:
    - column:
        OID: .1.3.6.1.2.1.55.1.8.1.3
        name: ipv6AddrAddress
      tag: ipv6_address_type
    - column:
        OID: .1.3.6.1.2.1.55.1.8.1.2
        name: ipv6AddrPfxLength
      tag: ipv6_prefix_length

    - column:
        name: ipv6_tag_static_1
        OID: 1.3.6.1.6.3.1135.6169.this_is_a_test
```

I am getting only static tag value, but not the static metrics:

```
IP::ipv6_address_metadata,device_ip=209.50.158.253,device_name=edge01_tee,index=621.254.128.0.0.0.0.0.0.94.94.171.11.173.1.71.192,instrumentation.name=juniper-mx-router,ipv6_address_type=2,ipv6_prefix_length=64,ipv6_tag_static_1=this_is_a_test,tags.dc=iad1,tags.kentik.device_id=32645,tags.kentik.model=MX80,tags.kentik.vendor=Juniper\ Networks,tags.type=edge ipv6_address_status=1i 1667254108
```

**Comment by i3149** [comment]
What are you expecting? I'm seeing this:

```
./bin/ktranslate -snmp snmp.yaml -format influx | grep static
2022-11-08T11:33:13.921 ktranslate/(34490) [Info] KTranslate>mabel Adding device metric .1.3.6.1.6.3.1136.6169.3 -> ipv6_address_static_value_1
SYNOLOGY-DISK-MIB::disk,device_ip=10.10.0.251,device_name=mabel,instrumentation.name=disk_station,tags.level=provider,tags.test=one,tags.type=nas ipv6_address_static_value_1=3i 1667936016
SYNOLOGY-DISK-MIB::disk,device_ip=10.10.0.251,device_name=mabel,instrumentation.name=disk_station,tags.level=provider,tags.test=one,tags.type=nas ipv6_address_static_value_1=3i 1667936046
SYNOLOGY-DISK-MIB::disk,device_ip=10.10.0.251,device_name=mabel,instrumentation.name=disk_station,tags.level=provider,tags.test=one,tags.type=nas ipv6_address_static_value_1=3i 1667936076
SYNOLOGY-DISK-MIB::disk,device_ip=10.10.0.251,device_name=mabel,instrumentation.name=disk_station,tags.level=provider,tags.test=one,tags.type=nas ipv6_address_static_value_1=3i 1667936106
```

With this setup:

```
  # Table of hard drive details
  - MIB: SYNOLOGY-DISK-MIB
    table:
      name: diskTable
      OID: 1.3.6.1.4.1.6574.2.1
    symbols:
      # Synology disk status
      - name: diskStatus
        OID: 1.3.6.1.4.1.6574.2.1.1.5
        enum:
          normal: 1
          initialized: 2
          notInitialized: 3
          systemPartitionFailed: 4
          crashed: 5
      # Synology disk temperature (C)
      - name: diskTemperature
        OID: 1.3.6.1.4.1.6574.2.1.1.6
      - name: ipv6_address_static_value_1
        OID: 1.3.6.1.6.3.1136.6169.3
```
