### ISSUE TITLE
remove hardcoded device SNMP metadata

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#461]
In the file `pkg/inputs/snmp/metadata/device_metadata.go:`

There are some number of hardcoded variables

```
	SNMP_device_metadata_oids = func() *orderedmap.OrderedMap {
		m := orderedmap.NewOrderedMap()
		m.Set(".1.3.6.1.2.1.1.1.0", SNMP_sysDescr)
		m.Set(".1.3.6.1.2.1.1.2.0", SNMP_sysObjectID)
		m.Set(".1.3.6.1.2.1.1.4.0", SNMP_sysContact)
		m.Set(".1.3.6.1.2.1.1.5.0", SNMP_sysName)
		m.Set(".1.3.6.1.2.1.1.6.0", SNMP_sysLocation)
		m.Set(".1.3.6.1.2.1.1.7.0", SNMP_sysServices)
		m.Set(".1.3.6.1.6.3.10.2.1.1.0", SNMP_engineID)
		return m
	}()
```

Their usage in the `func NewDeviceMetadata` overrides any use of the in the snmp-profiles.

For this reason, I am not able to use sysDescr variable in the snmp-profiles, especially to parse it using regex and extract the valuable metadata information which is there.

AFAIK, these hardcodes are used in two places:
- func NewDeviceMetadata
- func GetBasicDeviceMetadata

According to the comment in the code:
```
// Super basic loop to get info for discovery.
func GetBasicDeviceMetadata(log logger.ContextL, server *gosnmp.GoSNMP) (*kt.DeviceMetricsMetadata, error) {
```

the second one is used for discovery and we can leave it there. 

Can we remove these hardcoded variables from hardcoded collection and use purely snmp-profiles to rely on them?

**Comment by i3149** [comment]
I don't think your understanding here is correct. If you look at the code here: https://github.com/kentik/ktranslate/blob/main/pkg/inputs/snmp/metadata/device_metadata.go#L55

```
if len(deviceMetadataMibs) > 0 {
		oids := getFromCustomMap(deviceMetadataMibs)
		for _, oid := range oids {
			mib := deviceMetadataMibs[oid]
			mibs[oid] = mib
			log.Infof("Adding custom device metadata oid: %s -> %s %v", oid, mib.GetName(), mib.OtherTables)
		}
	} else {
		// Copy the global values into this map which is per device.
		for el := SNMP_device_metadata_oids.Front(); el != nil; el = el.Next() {
			mibs[el.Key.(string)] = nil
		}
	}
```

You can see that these default sysoid mibs are only used if there are no custom device mibs to poll. So you should be able to put whatever device level mibs you want in without breaking things. 

To keep backwards compatibility I'd rather not change things here.

**Comment by dpajin-kentik** [comment]
it is also loaded in basic here and further processed in that way: https://github.com/kentik/ktranslate/blob/5a0a0c35b36f180513404ad1af423b2d96057bcb/pkg/inputs/snmp/metadata/device_metadata.go#L51

I don't understand the code completely, but I see the behavior:

Having this profile

```yaml
# Removed system-mib.yml and using my definition on device metadata
---
extends:
  #- system-mib.yml
  - if-mib.yml
  #- interfaces.yml
  - ip-mib.yml
  - bgp4-mib.yml
  - ospf-mib.yml
  - host-resources-mib.yml
  - entity-mib.yml

metric_tags:
  # Tags from SYSTEM-MIB which we need to parse in the Juniper specific way
  - column:
      OID: 1.3.6.1.2.1.1.5.0
      name: sysName
  - column:
      OID: 1.3.6.1.2.1.1.6.0
      name: sysLocation
  - column:
      OID: 1.3.6.1.2.1.1.2.0
      name: sysObjectID
      allow_duplicate: true
  - column:
      OID: 1.3.6.1.6.3.10.2.1.1.0
      name: snmp-engine-id

# This one is important, I want ot use sysDescr for parsing but due to hardcoded OID value I am not able to, as this is not processed**

  - column:
      OID: 1.3.6.1.2.1.1.1.0
      name: sysDescr_parsing
      conversion: "regexp:(?P<sysDescr>(?P<vendor>Juniper Networks), Inc\\. (?P<model>\\S+).*kernel (?P<os_name>\\S+).*\\s(?P<os_version>[\\w\\-]+\\.[\\w\\-]+\\.[\\w\\-]+).*)"
      #conversion: "regexp:(?P<os_name>JUNOS)"

  # Vendor specific OIDS
  - column:
      OID: 1.3.6.1.4.1.2636.3.1.3.0
      name: serial_number
  - column:
      OID: 1.3.6.1.4.1.2636.3.1.2.0
      name: product_name
```

This is what I get from the latest ktranslate:

```bash
# field SysDescr is with the capital letter and the same from SysLocation, SysName, etc.
# This is not coming from profile since this is not written with the capital letter but the smallcaps
# The profile conversion is not used - no vendor or model or os_name fields
# but I have serial_number and product_name which are not overlapping with OIDs with hardcoded ones
device,SysDescr=Juniper\ Networks\,\ Inc.\ qfx5100-48s-6q\ Ethernet\ Switch\,\ kernel\ JUNOS\ 14.1X53-D35.3\,\ Build\ date:\ 2016-02-29\ 23:39:06\ UTC\ Copyright\ (c)\ 1996-2016\ Juniper\ Networks\,\ Inc.,SysLocation=iad1-dc3-5310,SysName=tor331.iad1,SysObjectID=.1.3.6.1.4.1.2636.1.1.1.4.82.5,device_ip=209.50.158.81,device_name=torXYZ.iad1,instrumentation.name=juniper-qfx-switches,product_name=Juniper\ QFX5100-48S-6Q\ Switch,serial_number=TA3717260199,src_addr=209.50.158.81,src_as=6169,src_as_name=CLOUD-42-6169,src_geo=US,tags.dc=iad1,tags.kentik.model=QFX510048S6Q,tags.kentik.vendor=Juniper\ Networks,tags.site=iad,tags.type=dc-leaf Uptime=2913414046i 1668002644
device,SysDescr=Juniper\ Networks\,\ Inc.\ JNP204\ [MX204]\ internet\ router\,\ kernel\ JUNOS\ 17.4R2.4\,\ Build\ date:\ 2018-08-17\ 02:20:40\ UTC\ Copyright\ (c)\ 1996-2018\ Juniper\ Networks\,\ Inc.,SysLocation=iad1-dc3-5012,SysName=edge03.iad1,SysObjectID=.1.3.6.1.4.1.2636.1.1.1.2.144,device_ip=209.50.158.251,device_name=edge03.iad1,instrumentation.name=juniper-mx-router,product_name=Juniper\ JNP204\ [MX204]\ Edge\ Router,serial_number=BP609,src_addr=209.50.158.251,src_as=6169,src_as_name=CLOUD-42-6169,src_geo=US,tags.dc=iad1,tags.kentik.model=JNP204,tags.kentik.vendor=Juniper\ Networks,tags.site=iad,tags.type=edge Uptime=912552174i 1668002645

# This is another "MIB" having device level metadata
# serial_number and product_name are visible as they are not overlapping, but others are suppressed - again hardcoded behavior
device_normalized,device_ip=209.50.158.81,device_name=torXYZ.iad1,instrumentation.name=juniper-qfx-switches,product_name=Juniper\ QFX5100-48S-6Q\ Switch,serial_number=TA3717260199,src_as=6169,src_as_name=CLOUD-42-6169,src_geo=US,tags.dc=iad1,tags.kentik.model=QFX510048S6Q,tags.kentik.vendor=Juniper\ Networks,tags.site=iad,tags.type=dc-leaf temperature=30i,memory_util=50i,uptime=2913413950i,cpu_util=19i,uptime_sec=157983155i 1668002644
device_normalized,device_ip=209.50.158.251,device_name=edge03.iad1,instrumentation.name=juniper-mx-router,product_name=Juniper\ JNP204\ [MX204]\ Edge\ Router,serial_number=BP609,src_as=6169,src_as_name=CLOUD-42-6169,src_geo=US,tags.dc=iad1,tags.kentik.model=JNP204,tags.kentik.vendor=Juniper\ Networks,tags.site=iad,tags.type=edge uptime=912552157i,cpu_util=1i,memory_util=12i,temperature=51i,uptime_sec=95024865i 1668002645
```

output from my local ktranslate with the change:

```bash
# no SysDescr with capital S, only sysDescr with smallcaps, which is expected from profile and model, os_name, os_version, etc

device,SysLocation=iad1-dc3-5310,SysName=tor331.iad1,SysObjectID=.1.3.6.1.4.1.2636.1.1.1.4.82.5,device_ip=209.50.158.81,device_name=torXYZ.iad1,instrumentation.name=juniper-qfx-switches,model=qfx5100-48s-6q,os_name=JUNOS,os_version=14.1X53-D35.3,product_name=Juniper\ QFX5100-48S-6Q\ Switch,serial_number=TA3717260199,src_addr=209.50.158.81,src_as=6169,src_as_name=CLOUD-42-6169,src_geo=US,sysDescr=Juniper\ Networks\,\ Inc.\ qfx5100-48s-6q\ Ethernet\ Switch\,\ kernel\ JUNOS\ 14.1X53-D35.3\,\ Build\ date:\ 2016-02-29\ 23:39:06\ UTC\ Copyright\ (c)\ 1996-2016\ Juniper\ Networks\,\ Inc.,tags.dc=iad1,tags.kentik.model=QFX510048S6Q,tags.kentik.vendor=Juniper\ Networks,tags.site=iad,tags.type=dc-leaf,vendor=Juniper\ Networks Uptime=2913343028i 1668001934000000000
device,SysLocation=iad1-dc3-5012,SysName=edge03.iad1,SysObjectID=.1.3.6.1.4.1.2636.1.1.1.2.144,device_ip=209.50.158.251,device_name=edge03.iad1,instrumentation.name=juniper-mx-router,model=JNP204,os_name=JUNOS,os_version=17.4R2.4,product_name=Juniper\ JNP204\ [MX204]\ Edge\ Router,serial_number=BP609,src_addr=209.50.158.251,src_as=6169,src_as_name=CLOUD-42-6169,src_geo=US,sysDescr=Juniper\ Networks\,\ Inc.\ JNP204\ [MX204]\ internet\ router\,\ kernel\ JUNOS\ 17.4R2.4\,\ Build\ date:\ 2018-08-17\ 02:20:40\ UTC\ Copyright\ (c)\ 1996-2018\ Juniper\ Networks\,\ Inc.,tags.dc=iad1,tags.kentik.model=JNP204,tags.kentik.vendor=Juniper\ Networks,tags.site=iad,tags.type=edge,vendor=Juniper\ Networks Uptime=912481404i 1668001937000000000

```

Also I don’t see “snmp-engine-id” anywhere…
