### ISSUE TITLE
FR: Add a mechanism for promoting attributes to user_tags

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#469]
As a user, I need the ability to mark specific attributes for `user_tag` elements so they are shipped to NR with the `tags.*` prefix. This allows me to take advantage of common fields from SNMP in various ways in the NR UI, like faceting and filtering my devices.

A solution could look something like this:

```yaml
global:
  user_tags:
    location: !"SysLocation"
```

```yaml
devices:
  deviceOne_192.168.0.1:
    ...
    user_tags:
      location: !"SysLocation"
```

this would promote the value of the `SysLocation` field (`1.3.6.1.2.1.1.6`) to a field named `tags.location` before exporting the payload to the NR API.
