### ISSUE TITLE
FR: Conversion regexp - have multiple regex rules

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#471]
As a user, I would like to be able to express multiple regex rules for conversion of the metadata to additional tags.

In some cases, a metadata field can have string expressed in different forms and the single regex expression is not enough to match all of the variations. 

I would propose using the “conversion” field also as dictionary for this and possibly other complicated things, but keep possibility that is string to keep backwards compatibility and simple use-cases. 

For example:
```yaml
- column:
      OID: 1.3.6.1.2.1.1.1.0
      name: sysDescr
      conversion:
        regexp:
          - "regex_1"
          - "regex 2"
          - "regex 3"
```
