### ISSUE TITLE
FR: conversion rate and diff

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#472]
As a user, I want to easily get the rate from the counter metrics and save them into separate metrics:

I propose that we use “conversion” methods for this, for example:
```yaml

metrics:
  - MIB: IF-MIB
    table:
      OID: 1.3.6.1.2.1.2.2
      name: ifTable
    symbols:
      - name: ifHCInOctets
        OID: 1.3.6.1.2.1.31.1.1.1.6
        tag: in-octets
        conversion:
          rate: "in-bps"
        or 
        conversion: "rate:in-bps"

      - name: ifInErrors
        OID: 1.3.6.1.2.1.2.2.1.14
        tag: in-errors
        conversion:
          diff: "in-errors-diff"
```
