### ISSUE TITLE
FR: snmp-profiles - add support for conversion or enum to save "string" value in the configured metric name

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#506]
We have a support in the snmp-profiles to have a metric field which is normally integer as enum type. 
However, the enum conversion does not have an effect, as the value is anyway sent as a integer value, which is okay. 
I would like to have an option to send the resulting enum string value as a metric as well, by being able to configure the additional metric name for the enum string value.

For example, this can be the configuration:
```
  - MIB: OSPF
    table:
      OID: 1.3.6.1.2.1.14.10    # ospfNbrTable(10)
      name: neighbors
    symbols:

      - tag: adjacency-state
        OID: 1.3.6.1.2.1.14.10.1.6
        name: ospfNbrState
        enum:
          DOWN: 1
          ATTEMPT: 2
          INIT: 3
          TWO_WAY: 4
          EXSTART: 5
          EXCHANGE: 6
          LOADING: 7
          FULL: 8
        conversion: "enum_to_metric:adjacency-state_str"
```
The result of this would be in case that the `adjacency-state=8` we have additional metric of string type with `adjacency-state_str=FULL`
