### ISSUE TITLE
snmp-profiles: tags enum values in upper case, sometimes returned in lowercase

### ISSUE THREAD

**Issue by dpajin-kentik** [kentik/ktranslate#509]
I have an issue that the metric tag as enum with capital letters is sometimes returned as a lowercase 
```

      - tag: components:type
        column:
          OID: .1.3.6.1.2.1.47.1.1.1.1.5
          name: entPhysicalClass
          enum:
            OTHER: 1
            UNKNOWN: 2
            CHASSIS: 3
            BACKPLANE: 4
            CONTAINER: 5
            POWER_SUPPLY: 6
            FAN: 7
            SENSOR: 8
            MODULE: 9
            PORT: 10
            STACK: 11
            CPU: 12
```
The values returned are sometimes in lowercase:
I don't have any other profile with the same OID or same 
```
/components,description=Transceiver\ Port\ Container\ Gi1/1,device_ip=198.186.190.9,device_name=cat6509,index=1025,name=Transceiver\ Port\ Container\ Gi1/1,parent=1024,parent-position=1,removable=false,type=container fru=2i 1670939767
/components,description=module\ 2\ power-output-fail\ Sensor,device_ip=198.186.190.9,device_name=cat6509,index=2002,name=module\ 2\ power-output-fail\ Sensor,parent=2000,parent-position=1,removable=false,type=sensor fru=2i 1670939767
/components,description=Te2/3,device_ip=198.186.190.9,device_name=cat6509,index=2034,name=Transceiver\ Port\ Te2/3,parent=2000,parent-position=3,removable=false,type=port fru=2i 1670939767
/components,description=WS-F6K-PFC3BXL\ Policy\ Feature\ Card\ 3\ sub-module\ of\ 1,device_ip=198.186.190.9,device_name=cat6509,index=1021,mfg-name=Cisco\ Systems,model=WS-F6K-PFC3BXL,name=WS-F6K-PFC3BXL\ Policy\ Feature\ Card\ 3\ Rev.\ 1.4,parent=1020,parent-position=1,removable=true,serial-no=SAL09169NV9,tags.type=spine,type=MODULE fru=1i 1670939767
/components,description=WS-C6503-E,device_ip=198.186.190.9,device_name=cat6509,hardware-version=V02,index=1017,mfg-name=Cisco\ Systems,model=WS-C6503-E,name=Cisco\ Systems\ Catalyst\ 6500\ 3-slot\ Chassis\ System,parent-position=-1,removable=true,serial-no=FOX111208YZ,type=CHASSIS fru=1i 1670939767
/components,description=PS\ 1\ PWR-950-AC,device_ip=198.186.190.9,device_name=cat6509,index=11,mfg-name=Cisco\ Systems\,\ Inc.,model=PWR-950-AC,name=AC\ power\ supply\,\ 950\ watt\ 1,parent=10,parent-position=1,removable=true,serial-no=ABC06260038,type=POWER_SUPPLY fru=1i 1670939467
```

The behavior is consistent in the sense that the same enum value will always be returned in the same manner for the same device. However, it can differ for different device.
