### ISSUE TITLE
FR: Revisiting trap indexes

### ISSUE THREAD

**Issue by Mesverrum** [kentik/ktranslate#547]
Following on from #425, at that time for the example scenario we were dealing with we had traps with multiple varbinds and multiple indexes, but the payload also showed the Index value so we opted not to store them as a separate field.  Now we are running into traps the do not include the Index as part of any varbind and we would need to extract it.

So if we take that in combination with the other scenario we ran into I think we may need to capture an Index attribute for each varbind

We need a plan to be able to cover both of these potential traps and make them useful.

```
".1.3.6.1.2.1.1.3.0": 496553183,
".1.3.6.1.2.1.15.3.1.14.10.51.128.62": "\u0004",
".1.3.6.1.2.1.15.3.1.2.10.51.128.62": 1,
".1.3.6.1.4.1.9.9.187.1.2.1.1.7.10.51.128.62": "hold time expired",
".1.3.6.1.4.1.9.9.187.1.2.1.1.8.10.51.128.62": 3,
"TrapOID": ".1.3.6.1.4.1.9.9.187.0.1",
```

and also the situation we ran into on the other issue where each varbind has a separate set of indexes

```

traps:
  - trap_oid: 1.3.6.1.4.1.12196.13.3.1.2
    trap_name: rSstateChange
    events:
      # Unique VS Id
      - name: vSidx
        OID: 1.3.6.1.4.1.12196.13.1.1.1.*
      # IP address of VS Differented by AddressType
      - name: vSip
        OID: 1.3.6.1.4.1.12196.13.1.1.2.*
      # VS port number
      - name: vSport
        OID: 1.3.6.1.4.1.12196.13.1.1.3.*
      # VS address type
      - name: vSaddrtype
        OID: 1.3.6.1.4.1.12196.13.1.1.4.*
      # Name of the VS
      - name: vSname
        OID: 1.3.6.1.4.1.12196.13.1.1.13.*
      # IP address of RS
      - name: rSip
        OID: 1.3.6.1.4.1.12196.13.2.1.2.*
      # RS port number
      - name: rSport
        OID: 1.3.6.1.4.1.12196.13.2.1.3.*
      # RS address type
      - name: rSaddrtype
        OID: 1.3.6.1.4.1.12196.13.2.1.4.*
      # Unique Id of RS
      - name: rSidx
        OID: 1.3.6.1.4.1.12196.13.2.1.5.*
      # current state of RS
      - name: rSstate
        OID: 1.3.6.1.4.1.12196.13.2.1.8.*
```
