### ISSUE TITLE
FR: Ability to embed static values directly in the profile

### ISSUE THREAD

**Issue by Mesverrum** [kentik/ktranslate#564]
Looking for a syntax that would allow users to define attributes and values inside the SNMP and trap profiles, independent of device tagging.  For example to help with directing all BGP related traps they could add an attribute that they would key into to direct the event to the team who handles routing, or if a vmware trap comes in they would be able to route it to the virtualization team.

This would primarily be used with cases where customers are using their own modified profiles.

Thinking in the trap profile adding something like

```
traps:
  - trap_oid: 1.3.6.1.4.1.6876.4.3
    trap_name: vmwVCNotifications
    drop_undefined: true
    events:
      - name: vmwVpxdOldStatus
        OID: 1.3.6.1.4.1.6876.4.3.304.0
        tag: old_status
      - name: vmwVpxdNewStatus
        OID: 1.3.6.1.4.1.6876.4.3.305.0
        tag: new_status
      - name: vmwVpxdObjValue
        OID: 1.3.6.1.4.1.6876.4.3.306.0
        tag: object_value
      - name: vmwVpxdTargetObj
        OID: 1.3.6.1.4.1.6876.4.3.307.0
        tag: object_name
      - name: vmwVpxdTargetObjType
        OID: 1.3.6.1.4.1.6876.4.3.308.0
        enum:
          unknown: 1
          host: 2
          vm: 3
          other: 4
        tag: object_type
    attributes:
      responsible_team: vmware
```
