### ISSUE TITLE
SNMP configuration is ignoring the cidrs and ignore_list settings

### ISSUE THREAD

**Issue by wuetz** [kentik/ktranslate#579]
Hello all,

i just noticed, that the ktranslate for the snmp discovery is not respecting the `cidrs` and the `ignore_list` attributes.
It seems to do the snmp discovery in the full network and does not care about my CIDRs I have listed there.

Example:
```yaml
discovery:
  cidrs: 
  - 10.101.1.1/32
  - 10.101.1.2/32
  ignore_list:
  - 10.101.102.1
  - 10.101.101.1
  - 10.101.103.1
  check_all_ips: false

```
I do see in the docker logs, that snmp is using an ignored host: `KTranslate Client SNMP: Running SNMP for <HOSTNAME> on 10.101.101.1`

I'm using the latest version of kentik's ktranslate docker image v2.

Any help is very appreciated.
