### ISSUE TITLE
🐛 - Trap collection isn't using the 'device_name' property

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#614]
We have a `v1.12.1` collector running to gather traps; which are showing up successfully in the logs:

ex:
```
KTranslate got trapdata from 10.126.102.11, EngineID 
```

Sample of the config file:
```yaml
devices:
    trap_device:
        device_name: $DEVICE_NAME
        device_ip: 10.126.102.11
        provider: kentik-trap-device
trap:
    listen: 0.0.0.0:1620
    community: $COMMUNITY_STRING
    version: v2c
    transport: ""
    v3_config: null
    trap_only: false
discovery:
    cidrs:
        - 10.126.102.11/32
    ignore_list: []
    debug: false
    ports:
        - 161
        - 162
    default_communities:
        - $COMMUNITY_STRING
    use_snmp_v1: false
    default_v3: null
    add_devices: true
    add_mibs: true
    threads: 4
    replace_devices: true
    check_all_ips: true
    kentik: null
global:
    poll_time_sec: 300
    drop_if_outside_poll: false
    mib_profile_dir: /etc/ktranslate/profiles
    mibs_db: ""
    mibs_enabled:
        - IF-MIB
    timeout_ms: 3000
    retries: 0
    global_v3: null
    response_time: false
    purge_devices_after_num: 0
    no_device_hardcoded_oids: false
    user_tags: {}
    match_attributes: {}
    providers: {}
    jitter_time_sec: 0
```

The traps are all successfully collected and sent; but the value received for `device_name` is the IP address. 

ex:
<img width="442" alt="Query your data New Relic One 2023-09-28 at 4 37 41 PM" src="https://github.com/kentik/ktranslate/assets/30831476/dfb7c0f6-1e45-4419-9957-724f1bc6dbba">
