### ISSUE TITLE
Feature request to use multiple community strings on a single device

### ISSUE THREAD

**Issue by al3kh** [kentik/ktranslate#652]
Hi,
We have few FortiGate devices which have Virtual domain that needs to be specified in the snmpwalk command after the community string for them to be monitored in New relic.
Also can we try to access it like- access the device via $COMMUNITY_1, and then access a VDOM via $COMMUNITY_n?
Example- We are using following command for BGP output on that device- "snmpwalk -v2c -c '$COMMUNITY_1'-$COMMUNITY_n 10.144.66.99 1.3.6.1.2.1.15.3"
Documentation for reference- https://community.fortinet.com/t5/FortiGate/Technical-Tip-SNMP-monitoring-of-BGP-and-OSPF-neighbors-in/ta-p/192879?externalID=FD44153

Thanks & Regards,
Alekh
SRE, Copart

**Comment by i3149** [comment]
Sure, should be doable.

**Comment by al3kh** [comment]
@i3149 how we have to make changes in the snmp config file for this?

**Comment by i3149** [comment]
I'll need to add this in as a custom feature.

**Comment by al3kh** [comment]
ok. do we have any ETA on this @i3149

**Comment by i3149** [comment]
I thought about this some more and I think you can just manually edit the `snmp-base.yaml` file to include the device multiple times. Set a different device name and community string and things should just work. For example:

```
devices:
    bart__base:
        device_name: bart
        device_ip: 192.168.0.200
        snmp_comm: $COMMUNITY_1
    bart__n:
        device_name: bart_n
        device_ip: 192.168.0.200
        snmp_comm: $COMMUNITY_1-$COMMUNITY_n
```
Each entry will be polled separately and the data for each vdom will be correctly returned. 

Looking at https://opennms.discourse.group/t/how-to-query-fortinet-vdoms/371 for more information on vdoms.
