### ISSUE TITLE
Client IP tracking

### ISSUE THREAD

**Issue by nijugeorge173** [kentik/ktranslate#670]
In a setup where remote host forwards traps to NGINX LB which connects to upstream server ( cluster having one container per server) the remote host IP is not visible on trap received at upstream server instead the LB IP is recorded. Any suggestions on what to do? Any recommendations for a setup running 8000 devices?

**Comment by i3149** [comment]
Can you use snmpv3 and `ContextEngineID`? If this is present, the device is first identified via this id, falling back to IP if no luck. For example, `engine_id: dead::beef` in the config yaml.

**Comment by nijugeorge173** [comment]
@i3149 Is there documentation or more detailed example for this , I could use that info to understand and guide

**Comment by i3149** [comment]
Say you have this device in your snmp.yaml file:

```yaml
devices:
    bart__192.168.0.200:
        device_name: bart
        device_ip: 192.168.0.200
...
        engine_id: 80:00:1f:88:80:67:96:34:73:68:e2:b9:65:00:00:00:00
```

Then when ktrans gets a trap, first it will look up and see if the engine id in the v3 packet matches any in the yaml file. If it does, it will use the device name bart and so on. Should all be pretty automatic, nothing to configure. If no match, it falls back to ip based matching.
