### ISSUE TITLE
[Feature request] Allow negative matches for regex in match_attributes

### ISSUE THREAD

**Issue by maxlemieux** [kentik/ktranslate#702]
This request is to provide an equivalent feature to work around the lack of negative lookahead patterns in Golang regex for [match_attributes](https://docs.newrelic.com/docs/network-performance-monitoring/advanced/advanced-config/#match_attributes-attribute).

Example which doesn't work (container will crash): 

```
match_attributes:
  "!if_interface_name": "^(?!foobarbaz\b)\\S+"
```

It would be great if there was an operator to negate the match. 

Example of workaround for this issue in Golang regex: https://regex101.com/library/7lMqca?page=862

**Comment by i3149** [comment]
Will this work for you?

```yaml
        match_attributes:
            if_interface_name: enp1s0
            DOES_NOT_MATCH: true
```

A long time ago, the `DOES_NOT_MATCH` special case was added. It will invert any matches for a `match_attributes` block where it is present.
