### ISSUE TITLE
Feature Request: Monitor OSPF data in Load Balancer Partitions

### ISSUE THREAD

**Issue by al3kh** [kentik/ktranslate#709]
Hi,
Currently NR does not support pulling snmp metrics from partitions. We are looking for OSPF polling from partitions. Can you please implement this feature for loadbalancer devices.
Thanks
Alekh
SRE
Copart

**Comment by i3149** [comment]
Sure, would it be possible to share a snmpwalk?

**Comment by al3kh** [comment]
Hi @i3149 PFA the snmpwalk of the device. Also I am attaching a screenshot where it shows the output after giving the partition with the community string.
![Screenshot 2024-05-14 063817](https://github.com/kentik/ktranslate/assets/69621334/a3aeb32f-ccc7-46aa-9364-6b9f5c8e1fce)
[10.144.64.25snmpwalk.txt](https://github.com/kentik/ktranslate/files/15307769/10.144.64.25snmpwalk.txt)

**Comment by al3kh** [comment]
@i3149 hi, do we have any update/ ETA on this?

**Comment by al3kh** [comment]
@i3149 hi, any updates on this issue yet?

**Comment by i3149** [comment]
Sorry for the delay. I think you are talking about something like this? https://thwack.solarwinds.com/products/network-performance-monitor-npm/i/feature-requests/a10-layer3-partition-snmp-polling-support

The way I've suggested you make this work with ktranslate before is have one device in the snmp yaml file for each partition. For example, 

```yaml
devices:
  Ladie__3.86.164.113:
    device_name: Ladie
    device_ip: 3.86.164.113
    snmp_comm: snmpstring@1
  Ladie__3.86.164.114:
    device_name: Ladie
    device_ip: 3.86.164.113
    snmp_comm: snmpstring@2
```

ktranslate will poll these separately and NR is smart enough to put them together in the UI. I can't find the issue where people hit this before but I believe its working for them.
