### ISSUE TITLE
💡 `GetCondition` needs to respect string matching as well as integer values

### ISSUE THREAD

**Issue by thezackm** [kentik/ktranslate#720]
revisiting PR #350 here...

The [GetCondition](https://github.com/kentik/ktranslate/blob/65e861175b50a96ecffa85ce7659611ed737092c/pkg/inputs/snmp/mibs/profile.go#L950-L968) function looks like it will error if the comparison is anything but an integer right now.

We have a need to expand this functionality to support a string match as well for OIDs that use the `SnmpAdminString` type like this:
```yaml
      - name: cempMemPoolHCUsed
        OID: 1.3.6.1.4.1.9.9.221.1.1.1.1.18
        poll_time_sec: 60
        tag: MemoryUsed
        allow_duplicate: true
        condition: cempMemPoolName="DP System memory"
```
