### ISSUE TITLE
[Feature] Add no_use_bulkwalkall as an option for discovered devices

### ISSUE THREAD

**Issue by araddas** [kentik/ktranslate#764]
We have a subset of devices on a specific subnet that do not play nicely with BULKWALK. We would like to add `no_use_bulkwalkall: true` to all discovered devices, manually defining this parameter per device will not scale within our environment. Ideally we would be able to define this in the discovery or global section, I'm not sure which section makes the most sense, but the following are some examples of how I think it should work.

**Possible Discovery Example**

```
discovery:
    cidrs:
        - 1.2.3.4/28
    ignore_list: []
    debug: false
    ports:
        - 161
    default_communities: []
    use_snmp_v1: false
    default_v3: aws.sm.my-secret-snmp-creds
    add_devices: true
    add_mibs: true
    threads: 4
    replace_devices: true
    check_all_ips: true
    kentik: null
    no_use_bulkwalkall: true
```

**Possible Global Example**
```
  global:
    poll_time_sec: 60
    drop_if_outside_poll: false
    mib_profile_dir: /etc/ktranslate/profiles
    mibs_db: /etc/ktranslate/mibs.db
    mibs_enabled: []
    timeout_ms: 20000
    retries: 0
    global_v3: null
    response_time: true
    ping_interval_sec: 60
    no_device_hardcoded_oids: false
    user_tags:
    jitter_time_sec: 0
    fast_poll: false
    watch_profile_changes: false
    save_mds_cache: false
    no_use_bulkwalkall: true
```

**Comment by i3149** [comment]
Easiest is to define in the discovery section for me. Then this value would get added to discovered devices as the are found. Would you want to further limit its application by subnet? EG, something like:

```yaml
discovery:
    cidrs:
        - 1.2.3.4/28
    ignore_list: []
    debug: false
    ports:
        - 161
    default_communities: []
    use_snmp_v1: false
    default_v3: aws.sm.my-secret-snmp-creds
    add_devices: true
    add_mibs: true
    threads: 4
    replace_devices: true
    check_all_ips: true
    kentik: null
    no_use_bulkwalkall: 
      - 1.2.3.4/30
```

Or just keep as a boolean for now?
