### ISSUE TITLE
[Feature Request] Add additional configuration items to filter Netbox devices

### ISSUE THREAD

**Issue by MattiasSegerdahl** [kentik/ktranslate#812]
Hi team,

First off, thank you for the excellent work on ktranslate—it’s been instrumental in automating our SNMP-based discovery pipeline.

We’re currently using the netbox integration in the discovery section of the SNMP configuration, and it works well for basic filtering by site and ip_to_pick. However, as our NetBox instance becomes more richly populated and structured, we’d greatly benefit from enhanced filtering capabilities.

Feature Request

I would like to request support for additional filtering options in the netbox configuration block of snmp-base.yaml:
	•	tenant – Filter devices based on assigned tenants
	•	role – Filter devices based on device roles
	•	location – Filter by physical or logical location
	•	status – Filter based on device operational status (e.g., active, staged, decommissioned)
	•	custom_fields – Filter devices using custom key/value metadata defined in NetBox

Use Case

This added filtering flexibility would allow us to:
	•	Limit SNMP polling to only active or production-ready devices
	•	Segment polling responsibilities across tenants or business units
	•	Selectively monitor devices based on logical roles (e.g., only “edge-routers”)
	•	Support more granular automation scenarios, especially in multi-tenant environments
	•	Fully leverage NetBox as our single source of truth

Proposed Configuration Example
```
netbox:
  host: http://netbox.default.svc.cluster.local
  token: <redacted>
  site: Gothenburg
  tenant: infra
  role: edge-router
  location: dc1
  status: active
  custom_fields:
    monitor: true
  ip_to_pick: oob
```

This would dramatically reduce the need for manual device filtering logic outside of ktranslate and improve operational clarity.

Please let me know if this is something on the roadmap or if there’s any way I can help contribute to the feature.

Thanks again for your time and the great tooling!
