### ISSUE TITLE
Feature Request: Support multiple values for NetBox filters (e.g., `tenant=A&tenant=B`)

### ISSUE THREAD

**Issue by MattiasSegerdahl** [kentik/ktranslate#816]
### Feature Request: Support multiple values for NetBox filters (e.g., `tenant=A&tenant=B`)

**Description:**

Currently, the NetBox integration in ktranslate only supports a single value for filters such as `tenant`, `status`, `site`, etc. For example:

```yaml
netbox:
  url: http://netbox.default.svc.cluster.local/api/dcim/devices/
  token: <TOKEN>
  site: got
  status: active
  ip_to_pick: oob
  tenant: A
```

However, the NetBox REST API supports multiple values for a single query parameter, like:

```
?tenant=A&tenant=B
```

**Feature Request:**

It would be helpful if ktranslate allowed these filters to accept multiple values, enabling the use of `tenant=A&tenant=B`, `site=got&site=sto`, etc.

**Proposal:**

Update the NetBox integration config to support multiple values per filter, such as:

```yaml
netbox:
  tenant:
    - A
    - B
```

or

```yaml
netbox:
  tenant: A,B
```

**Benefit:**

This would improve flexibility and reduce the need for running multiple instances or applying post-processing logic to filter the results.

Let me know if this is feasible or if there's a preferred way to contribute a PR. Thanks!
