### ISSUE TITLE
Ktranslate does not reflect ping_interval_sec in the Device sect

### ISSUE THREAD

**Issue by qryuu** [kentik/ktranslate#823]
Summary
Ktranslate does not reflect ping_interval_sec in the Device section.

Description
Ping_interval_sec is set in the Device section in kKtranslate.
However, it is acting as if the value of poll_time_sec in the Global section has priority, and the ping_interval_sec setting is not reflected.

In the case of snmp-base2.yaml, the value is retrieved every 60 seconds as per poll_time_sec in the global section.

Data is not retrieved for snmp-base3.yaml

snmp-base2.yaml
```json: snmp-base2.yaml
devices:
  ping_only__10.0.17.52:
    device_name: ping_only
    device_ip: 10.0.17.52
    provider: kentik-ping
    ping_only: true
    ping_interval_sec: 30
global:
  poll_time_sec: 60
  mib_profile_dir: /etc/ktranslate/profiles
  mibs_db: /etc/ktranslate/mibs.db
  timeout_ms: 3000

``` 

snmp-base3.yaml
```json: snmp-base3.yaml
devices:
  ping_only__10.0.17.52:
    device_name: ping_only
    device_ip: 10.0.17.52
    provider: kentik-ping
    ping_only: true
    ping_interval_sec: 60
global:
  poll_time_sec: 30
  mib_profile_dir: /etc/ktranslate/profiles
  mibs_db: /etc/ktranslate/mibs.db
  timeout_ms: 3000

```

**Comment by i3149** [comment]
I'm having a hard time reproducing this behavior locally. When I run the config

```yaml
devices:
  ping_only__10.0.17.52:
    device_name: ping_only
    device_ip: 10.0.17.52
    provider: kentik-ping
    ping_only: true
    ping_interval_sec: 30
global:
  poll_time_sec: 60
  mib_profile_dir: /etc/ktranslate/profiles
  mibs_db: /etc/ktranslate/mibs.db
  timeout_ms: 3000
```

I see the log line `Ping Interval: 30s` 

And when I remove `ping_interval_sec` from the device section and put `ping_interval_sec: 60` into the global section I see `Ping Interval: 60s`. But when I put `ping_interval_sec: 30` back into the device section it takes priority. Can I get more detail on what you see which is showing the 60 sec polling interval?
